describe("health check", function()
  it("loads and exposes check()", function()
    local health = require("nvim-ask.health")
    assert.equals("function", type(health.check))
  end)

  it(":checkhealth nvim-ask produces a report", function()
    require("nvim-ask").setup({})
    assert.has_no.errors(function()
      vim.cmd("checkhealth nvim-ask")
    end)
    local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
    local report = table.concat(lines, "\n")
    assert.is_truthy(report:match("nvim%-ask"))
    assert.is_truthy(report:match("backend"))
  end)
end)
