local parser = require("nvim-ask.parser")

describe("parser.split_response", function()
  it("captures a fenced block with a c++ language tag", function()
    local r = parser.split_response("Here you go:\n```c++\nint x = 1;\n```")
    assert.equals("c++", r.lang)
    assert.equals("int x = 1;", r.code)
    assert.equals("Here you go:", r.text)
  end)

  it("tolerates an info string after the language", function()
    local r = parser.split_response("```csharp copy\nvar y = 2;\n```")
    assert.equals("csharp", r.lang)
    assert.equals("var y = 2;", r.code)
  end)

  it("returns all code blocks and mirrors the first in code/lang", function()
    local text = "First:\n```lua\nlocal a = 1\n```\nSecond:\n```lua\nlocal b = 2\n```"
    local r = parser.split_response(text)
    assert.equals(2, #r.blocks)
    assert.equals("local a = 1", r.blocks[1].code)
    assert.equals("local b = 2", r.blocks[2].code)
    assert.equals("local a = 1", r.code)
    assert.equals("First:\nSecond:", r.text)
  end)

  it("returns text only when there is no code", function()
    local r = parser.split_response("Just an explanation, no code.")
    assert.is_nil(r.code)
    assert.equals(0, #r.blocks)
    assert.equals("Just an explanation, no code.", r.text)
  end)

  it("returns code only when there is no prose", function()
    local r = parser.split_response("```python\nprint(1)\n```")
    assert.is_nil(r.text)
    assert.equals("print(1)", r.code)
  end)

  it("captures an unterminated fence", function()
    local r = parser.split_response("```lua\nlocal z = 9")
    assert.equals("local z = 9", r.code)
  end)
end)

describe("parser.extract_code_blocks", function()
  it("handles a fence without a language", function()
    local blocks = parser.extract_code_blocks("```\nplain\n```")
    assert.equals(1, #blocks)
    assert.is_nil(blocks[1].lang)
    assert.equals("plain", blocks[1].code)
  end)
end)

describe("parser.get_primary_code", function()
  it("returns the first block's code and lang", function()
    local code, lang = parser.get_primary_code("```go\nx := 1\n```")
    assert.equals("x := 1", code)
    assert.equals("go", lang)
  end)
end)
